import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/components/AuthProvider";
import { auth } from "@/auth"; // Importar auth para obtener sesión en servidor
import { Toaster } from 'sonner'; // Importar Toaster

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Convertir a async para poder usar await auth()
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Obtener la sesión del servidor
  const session = await auth();
  return (
    <html lang="es"> {/* Cambiar a español */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        // Mantener clases de fuente (comentario fuera de las props)
      >
        {/* Pasar la sesión al AuthProvider */}
        <AuthProvider session={session}>
          {children}
          <Toaster richColors position="top-right" /> {/* Añadir Toaster aquí */}
        </AuthProvider>
      </body>
    </html>
  );
}
